# Generated by Django 5.1.4 on 2024-12-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_day', models.IntegerField(help_text='Day of the month the salary is paid')),
                ('payment_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly')], default='Monthly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='esalary.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esalary.salaryschedule')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary', to='esalary.salary'),
        ),
    ]
